### ISSUE TITLE
Present Auth flow through modal 

### ISSUE THREAD

**Issue by markst** [darrarski/swift-google-drive-client#19]
I'd like to be able to present the auth flow in a modal rather than bumping a user out to browser.

i.e:

![Simulator Screen Recording - iPhone 13 mini - 2023-12-29 at 08 51 58](https://github.com/darrarski/swift-google-drive-client/assets/274318/48535634-de49-4ac8-b362-fc16f6450557)

**Comment by markst** [comment]
I guess this is just a case of creating my own web view controller and presenting from `openURL` such as:

```swift
let client = GoogleDriveClient.Client.live(
  config: .init(
    clientID: "{removed}",
    authScope: "https://www.googleapis.com/auth/drive.readonly",
    redirectURI: "{removed}"
  ),
  openURL: OpenURL { url in
     let webViewController = await SFSafariViewController(url: url)
     return await UIApplication.shared.keyWindow?.rootViewController?
        .present(webViewController, animated: true) != nil
  }
)
```

**Comment by darrarski** [comment]
Yes, you can customize how the library opens the sign-in URL by overwriting the `openURL` dependency. Default implementation delegates its job to SwiftUI's `openURL` environment value. The closure should return `true` if the URL was opened successfully, otherwise `false`.

```swift
let client = GoogleDriveClient.Client.live(
  /* ... */
  openURL: OpenURL { url in
    // Open the URL and return `true`
    // If the URL can't be opened, return `false`
  }
)
```
