### ISSUE TITLE
Awesome Library!!

### ISSUE THREAD

**Issue by strong84** [darrarski/swift-google-drive-client#24]
Sorry, I created this by mistake.
I ran into 403 forbidden error, but it was my mistake, setting with the wrong scope.

==========

I tried google official SDK, it raises many concerns.
It set 3 extra scopes by default:
1. openid
2. https://www.googleapis.com/auth/userinfo.profile
3. https://www.googleapis.com/auth/userinfo.email

And these scopes will be shown on the consent screen. and they can not be toggled off.
the screen ends up like this:
https://stackoverflow.com/questions/70765918/google-oauth-consent-screen-how-do-i-know-the-user-grants-the-requested-access

 I really love this approach.

Thanks for making this possible. Really hope this Library will be maintained in long term.

**Comment by darrarski** [comment]
Thanks for the kind words. I try to keep the library maintained in my spare time. Feel free to submit an issue in case you experience a problem, or would like to add more features. It's open source, I'm counting on the community's support! Pull requests are more than welcome :-)
